name: Publish update
on: [push]

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Setup cache
        uses: actions/cache@v2
        with:
        path: |
              ~/.cargo/registry
              ~/.cargo/git
              target
        key: ${{ runner.os }}-test-rustc-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Create release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-unknown-linux-gnu
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: aenterprise
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gearbot/twilight-http-proxy:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}



